<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TBZ.Middleware.Application\TBZ.Middleware.Application.csproj" />
    <ProjectReference Include="..\TBZ.Middleware.Domain\TBZ.Middleware.Domain.csproj" />
    <ProjectReference Include="..\TBZ.Middleware.Infrastructure\TBZ.Middleware.Infrastructure.csproj" />
    <ProjectReference Include="..\TBZ.Middleware.Workers\TBZ.Middleware.Workers.csproj" />
  </ItemGroup>

</Project>
