<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FuzzySharp" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SynOS.Data\SynOS.Data.csproj" />
    <ProjectReference Include="..\SynOS.Models\SynOS.Models.csproj" />
  </ItemGroup>

</Project>
