<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TBZ.Middleware.Api-e3b7c688-4299-4c12-9c3f-c6b71b80c58e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TBZ.Middleware.Infrastructure\TBZ.Middleware.Infrastructure.csproj" />
    <ProjectReference Include="..\TBZ.Middleware.Domain\TBZ.Middleware.Domain.csproj" />
    <ProjectReference Include="..\TBZ.Middleware.Workers\TBZ.Middleware.Workers.csproj" />
  </ItemGroup>

</Project>
