namespace SynOS.Models.Enums
{
    public enum BranchEventType
    {
        PATIENT_REGISTERED,
        VISIT_CREATED,
        VISIT_STARTED,
        VISIT_UPDATED,
        VISIT_CANCELLED, // ADDED
        BILL_GENERATED,
        DISCOUNT_APPLIED,
        PAYMENT_RECEIVED,
        PAYMENT_VOIDED, // ADDED
        RECEIVABLE_CREATED,
        RECEIVABLE_VOIDED, // ADDED
        VISIT_FINALIZED,
        VISIT_CORRECTED_AFTER_PAYMENT,
        SPECIMEN_ORDERED, // ADDED
        SPECIMEN_PLANNED, 
        SPECIMEN_COLLECTED, 
        SPECIMEN_REJECTED, 
        SPECIMEN_DELETED, // ADDED
        TEST_ADDED, // ADDED
        TEST_REMOVED, // ADDED
        RESULT_VERIFIED, // ADDED
        RESULT_DRAFT_STARTED, 
        REPORT_CREATED, // ADDED
        REPORT_READY_FOR_VERIFICATION, 
        REPORT_VERIFIED,
        REPORT_SIGNED, 
        REPORT_REVERTED, // ADDED
        REPORT_DELIVERED, 
        REPORT_READY,
        REFERRAL_CORRECTED,
        INVENTORY_SHORTAGE // ADDED
    }
}
