<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>SynOS.ico</ApplicationIcon>
    <AssemblyName>SynOS.ServerManager</AssemblyName>
    <RootNamespace>SynOS.ServerManager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="SynOS.ico" />
  </ItemGroup>

</Project>
