using System;
using System.Threading.Tasks;
using SynOS.Data;
using SynOS.Models.DTOs.Revenue;
using SynOS.Models.Entities.Revenue;

namespace SynOS.Services.Revenue
{
    /// <summary>
    /// Implements the write-only persistence for RevenueFacts.
    /// This service acts as the single write-gate for the Revenue Engine.
    /// </summary>
    /// <remarks>
    /// **ENGINE SEALED: WRITE-ONLY TRUTH**
    /// - This service is strictly for inserting new, immutable RevenueFacts.
    /// - It performs no reads, no validation beyond type binding, no business logic,
    ///   no aggregation, no updates, no deletes, and no external calls.
    /// - `DeclaredAt` is set at write time to reflect when the system received the declaration.
    /// - Returns only the ID of the created fact as an acknowledgement.
    /// </remarks>
    public class RevenueFactWriter : IRevenueFactWriter
    {
        private readonly SynOSDbContext _context;

        public RevenueFactWriter(SynOSDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Declares and persists a new immutable RevenueFact.
        /// </summary>
        /// <param name="command">The command containing the details of the revenue fact.</param>
        /// <returns>The Guid of the newly created RevenueFact.</returns>
        public async Task<Guid> DeclareRevenueFactAsync(DeclareRevenueFactCommand command)
        {
            // The RevenueFactId is optional in the command for caller-provided idempotency.
            // If not provided, a new one is generated by the system.
            var revenueFactId = command.RevenueFactId ?? Guid.NewGuid();

            var newFact = new RevenueFact
            {
                RevenueFactId = revenueFactId,
                OccurredAt = command.OccurredAt,
                DeclaredAt = DateTimeOffset.UtcNow, // Set at write time
                Amount = command.Amount,
                Currency = command.Currency,
                Direction = command.Direction,
                SourceType = command.SourceType,
                SourceReferenceId = command.SourceReferenceId,
                PaymentMode = command.PaymentMode,
                DeclaredByUserId = command.DeclaredByUserId,
                Notes = command.Notes,
                ExternalTransactionId = command.ExternalTransactionId
            };

            await _context.RevenueFacts.AddAsync(newFact);
            await _context.SaveChangesAsync();

            return newFact.RevenueFactId; // Return only the ID as per corrected instructions
        }
    }
}
